### PR TITLE
Update gamestats_key.txt

### PR DESCRIPTION
**Pull request by barronwaffles**
Processed NDS releases 0 - 4800

### CODE REVIEW

**Comment by sepalani** [comment]
Many thanks!

**Comment by barronwaffles** [comment]
No problem - I'll have the script parse the last half of the set tomorrow.

**Comment by sepalani** [comment]
BTW, does your script handle the old secrets, the ones like tetrisds and acrossingds?

**Comment by barronwaffles** [comment]
The current scan results are just the full/extended secret type, but the script logs files where it detects URLs but doesn't locate a stats key - hopefully this will reduce the match results for old type keys to a manageable level in the upcoming pass. Aware of any other potential indicators that would possibly provide additional result filtering?

**Comment by sepalani** [comment]
Besides URLs and regular expressions, no I don't have any. How do you detect URLs? Could you save the URLs list somewhere, if it's not too complicated? It might be useful to know which routes aren't implemented yet or which games might be worth investigating.

I usually just do a fgrep with ".asp" (a path regexp can be used for better filtering) as searching for "gamestats.gs" (usually used by old games like tetrisds and axingds) or "gamestats2.gs" might not be enough. The main issue with NDS games compared to Wii ones is that it's not necessarily stored in a single location (for instance, in the main.dol for the Wii) but can be in the arm9.bin or in (sometimes LZ11 compressed) overlays.

**Comment by barronwaffles** [comment]
Regex matching - although I'm assuming there's bound to be false negatives currently due to how fractured some of the addresses are stored internally.

URL logging/tracking wouldn't be a problem, I'll sort something out later this week and push a tools branch on my fork.

**Pull request merged**
